# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cpho3V5yKKGgJVg8sSWFP0qR6_aHF-xv
"""

import datetime
def countdown():
  while True:
    try: 
     a=int(input("Hour: "))
    except ValueError:
     print("please input integer")
    try: 
     b=int(input("minutes: "))
    except ValueError:
     print("please input integer")
    try: 
     c=int(input("Seconds: "))
    except ValueError:
     print("please input integer")
    break
   
  x= datetime.datetime(2022,12,12,a,b,c)
  from datetime import timedelta
  from time import sleep
  while x!= datetime.time(0,0,0):
    x=x+timedelta(seconds=-1)
    time = x.strftime("%H:%M:%S")
    print(time)
    sleep(1)

countdown()
