# -*- coding: utf-8 -*-
"""Craps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/141N35Bhfecd6po6RfNL-fAU66tNDBgWM
"""

import random
def game():
    i=0
    while True:
      print('If you want to continue playing the game, enter letter "p"=play, else any other key'.center(250))
      ipt=input("Do you want to continue playing ?")
      if ipt=='p':
          a=random.randint(1,6)
          b=random.randint(1,6)
          sum=a+b
          print('first dice ',a)
          print('second dice ',b)
          print('your score ',sum)
          if sum==7 or sum==11:
              print('You won'.center(250))
              
          elif sum==2 or sum==3 or sum==12:
              print('Casino won'.center(250))
             
          elif sum in[ 4,5,6,8,9,10]:
             print('This is the special case, you need to hit the goal number if you want to continue, press "y"=yes'.center(250))
             print('The goal number is ', sum)
             i=1
             
             while True:
               goal_a=random.randint(1,6)
               goal_b=random.randint(1,6)
               goal_sum=goal_a+goal_b
               q=input('do you want to start try N {} ? '.format(i)
               )
               if q=='y': 
                 print(goal_sum)
                 if sum==goal_sum:
                    print('you won')
                    print(goal_a)
                    print(goal_b)
                    break
                 elif goal_sum==7:
                   print('You Lose')
                   break
               else: break              
             case=3
      else: break

        
game()
